"""Mnemo core package."""

from .config import (
    EmbeddingConfig,
    FilesystemStorageConfig,
    LLMConfig,
    LLMRoleConfig,
    MnemoConfig,
    PluginConfig,
    QdrantStorageConfig,
    RerankerConfig,
    SQLiteStorageConfig,
    StorageConfig,
    SurrealDBStorageConfig,
)
from .registry import (
    PLUGIN_ENTRY_POINT_GROUP,
    PLUGIN_INTERFACE_VERSION,
    CapabilityKind,
    PluginCompatibilityError,
    PluginDescriptor,
    PluginDiscoveryError,
    PluginInterface,
    PluginInterfaceV1,
    PluginLoadResult,
    PluginRegistry,
    PluginSource,
    PluginValidationError,
    RegistrationConflictError,
    RegistrationDescriptor,
    RegistryError,
    RegistryFrozenError,
    RegistryState,
)

__version__ = "0.0.0"

__all__ = [
    "PLUGIN_ENTRY_POINT_GROUP",
    "PLUGIN_INTERFACE_VERSION",
    "CapabilityKind",
    "EmbeddingConfig",
    "FilesystemStorageConfig",
    "LLMConfig",
    "LLMRoleConfig",
    "MnemoConfig",
    "PluginCompatibilityError",
    "PluginConfig",
    "PluginDescriptor",
    "PluginDiscoveryError",
    "PluginInterface",
    "PluginInterfaceV1",
    "PluginLoadResult",
    "PluginRegistry",
    "PluginSource",
    "PluginValidationError",
    "QdrantStorageConfig",
    "RegistrationConflictError",
    "RegistrationDescriptor",
    "RegistryError",
    "RegistryFrozenError",
    "RegistryState",
    "RerankerConfig",
    "SQLiteStorageConfig",
    "StorageConfig",
    "SurrealDBStorageConfig",
    "__version__",
]
