"""Dedicated Manual Gemma 4:e4b Query Test Suite for Mnemo Phase 0-6 Pipeline.

This is an interactive and manual evaluation harness for testing the quality,
grounding, and citation accuracy of answers generated by gemma4:e4b against
the real Bhagavad Gita golden corpus.

Usage:
    uv run python scripts/manual_gita_qa.py
    uv run python scripts/manual_gita_qa.py --context 8192
    uv run python scripts/manual_gita_qa.py --context 16384
    uv run python scripts/manual_gita_qa.py --context 32768
    uv run python scripts/manual_gita_qa.py --question 1
    uv run python scripts/manual_gita_qa.py --question all
"""

from __future__ import annotations

import argparse
import asyncio
import contextlib
import os
import re
import time
from collections.abc import Sequence
from datetime import UTC, datetime
from pathlib import Path
from uuid import NAMESPACE_URL, UUID, uuid4, uuid5

from mnemo.config import (
    EmbeddingConfig,
    FilesystemStorageConfig,
    LLMConfig,
    LLMRoleConfig,
    MnemoConfig,
    PluginConfig,
    QdrantStorageConfig,
    RerankerConfig,
    SQLiteStorageConfig,
    StorageConfig,
    SurrealDBStorageConfig,
)
from mnemo.engine import FinalQAComponents, KnowledgeEngine
from mnemo.models import (
    Chunk,
    ContextItemKind,
    DocType,
    DocumentContextLabel,
    FinalQARequest,
    FinalQAResult,
    FinalQAStatus,
    MetadataFilter,
    Notebook,
    Session,
    Source,
    Turn,
    TurnRole,
)
from mnemo.tokenizers import O200KBaseTokenCounter
from pydantic import HttpUrl
from verify_phase_4_5_milestones import (
    _registry,
    _run_m4,
    _tokenizer_asset,
)

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data" / "manual-gita-qa"
MODEL = "gemma4:e4b"
RERANKER_MODEL = "cross-encoder/ms-marco-MiniLM-L6-v2"
EMBEDDING_MODEL = "nomic-embed-text"
COLLECTION_NAME = "mnemo_manual_qa_gita"

CONCEPTUAL_QUESTIONS: dict[str, str] = {
    "C1": "What does the Bhagavad Gita teach about duty?",
    "C2": "What does Krishna say about performing action without attachment to the results?",
    "C3": "What is Karma-yoga according to the Bhagavad Gita?",
    "C4": "What does the Bhagavad Gita teach about controlling the mind?",
    "C5": "What does Krishna teach about the relationship between knowledge and action?",
    "C6": "What does the Bhagavad Gita say about the nature of the self?",
    "C7": "What does Krishna teach Arjuna about fear and courage?",
    "C8": "What does the Bhagavad Gita teach about devotion to Krishna?",
    "C9": "What does the Bhagavad Gita say about equanimity?",
    "C10": "What does Krishna say about desire and its effect on a person's actions?",
    "C11": "How does the Bhagavad Gita describe the three modes of material nature?",
    "C12": "What does the Bhagavad Gita teach about renunciation?",
    "C13": "What does Krishna say about doing one's own duty rather than another's?",
    "C14": "What does the Bhagavad Gita teach about meditation?",
    "C15": "What is the purpose of action according to Krishna?",
}

EXACT_SHLOKA_QUESTIONS: dict[str, str] = {
    "S1": "Tell me Bhagavad Gita 2.47.",
    "S2": "What is Bhagavad Gita 2.47?",
    "S3": "Give me the shloka from Bhagavad Gita Chapter 2, Verse 47.",
    "S4": "What does Bhagavad Gita 2.47 say?",
    "S5": "Show me the Sanskrit shloka of Bhagavad Gita 2.47.",
    "S6": "Give me the verse and explain Bhagavad Gita 2.47.",
    "S7": "What is the teaching of Chapter 2 Verse 47?",
    "S8": "Quote Bhagavad Gita 2.47 and explain its meaning.",
    "S9": "Tell me Bhagavad Gita 2.11.",
    "S10": "Tell me Bhagavad Gita 2.13.",
    "S11": "What is Bhagavad Gita 2.20?",
    "S12": "What is Bhagavad Gita 2.48?",
    "S13": "What does Bhagavad Gita 2.50 teach?",
    "S14": "What is Bhagavad Gita 3.5?",
    "S15": "Give me the shloka from Bhagavad Gita Chapter 3, Verse 8.",
    "S16": "What does Bhagavad Gita 3.19 say?",
    "S17": "What is Bhagavad Gita 3.21?",
    "S18": "What does Bhagavad Gita 3.30 teach?",
    "S19": "What is Bhagavad Gita 4.7?",
    "S20": "What is Bhagavad Gita 4.8?",
    "S21": "Give me the shloka from Bhagavad Gita Chapter 4, Verse 34.",
    "S22": "What does Bhagavad Gita 6.5 say?",
    "S23": "What is Bhagavad Gita 6.6?",
    "S24": "What is Bhagavad Gita 9.22?",
    "S25": "What does Bhagavad Gita 12.13 teach?",
    "S26": "What is Bhagavad Gita 18.47?",
    "S27": "What does Bhagavad Gita 18.66 teach?",
}

TOPIC_SHLOKA_QUESTIONS: dict[str, str] = {
    "T1": "Tell me the Bhagavad Gita shloka about karma.",
    "T2": (
        "Which shloka says that one has a right to perform one's duty but not to the fruits"
        " of action?"
    ),
    "T3": "Give me the Bhagavad Gita verse about performing action without attachment.",
    "T4": "Which shloka teaches Nishkama Karma?",
    "T5": "Give me the shloka about doing your duty without attachment to results.",
    "T6": "Which verse says that one should perform one's prescribed duty?",
    "T7": "Tell me the Bhagavad Gita shloka about equanimity.",
    "T8": "Which shloka says that success and failure should be treated equally?",
    "T9": "Give me the shloka about controlling the mind.",
    "T10": "Which verse teaches that the mind can be one's friend or one's enemy?",
    "T11": "Give me the Bhagavad Gita shloka about the nature of the self.",
    "T12": "Which shloka says that the soul is never born and never dies?",
    "T13": "Give me the shloka about Krishna appearing when dharma declines.",
    "T14": "Which verse says 'Whenever there is a decline of dharma'?",
    "T15": "Give me the Bhagavad Gita verse about surrendering to Krishna.",
    "T16": "Which shloka teaches complete surrender to Krishna?",
    "T17": "Give me the shloka about devotion.",
    "T18": "Which verse describes the qualities of a devotee dear to Krishna?",
}

KARMA_GROUP_QUESTIONS: dict[str, str] = {
    "K1": "Tell me the Bhagavad Gita shloka on karma.",
    "K2": "Give me the shloka about performing one's duty without attachment.",
    "K3": "Which verse says one has a right to action but not to the fruits?",
    "K4": "Tell me Bhagavad Gita 2.47 and explain it.",
    "K5": "Which shloka is the famous Nishkama Karma verse?",
    "K6": "Give me the Sanskrit verse about कर्मण्येवाधिकारस्ते.",
    "K7": "What does Bhagavad Gita 2.47 teach about the fruits of action?",
    "K8": "Give me the verses surrounding Bhagavad Gita 2.47 that explain karma-yoga.",
    "K9": "Which Bhagavad Gita shloka says that action is better than inaction?",
    "K10": "Give me the shloka about performing prescribed duty.",
}

ALL_CATEGORIES: dict[str, dict[str, str]] = {
    "CONCEPTUAL QUESTIONS": CONCEPTUAL_QUESTIONS,
    "EXACT SHLOKA / VERSE QUESTIONS": EXACT_SHLOKA_QUESTIONS,
    "TOPIC → SHLOKA QUESTIONS": TOPIC_SHLOKA_QUESTIONS,
    "KARMA / KARMA-YOGA GROUP": KARMA_GROUP_QUESTIONS,
}

# Flat lookup table by key
ALL_QUESTIONS: dict[str, str] = {}
for group in ALL_CATEGORIES.values():
    ALL_QUESTIONS.update(group)


def _build_config(context_size: int) -> MnemoConfig:
    role = LLMRoleConfig(provider="ollama", model=MODEL, max_context_tokens=context_size)
    qdrant_url = os.environ.get("MNEMO_STORAGE_QDRANT_URL", "http://127.0.0.1:6333")
    ollama_url = os.environ.get("MNEMO_EMBEDDING_API_BASE", "http://127.0.0.1:11434")
    surrealdb_url = os.environ.get("MNEMO_STORAGE_SURREALDB_URL", "http://127.0.0.1:8001")
    surrealdb_defaults = SurrealDBStorageConfig()

    return MnemoConfig(
        storage=StorageConfig(
            filesystem=FilesystemStorageConfig(root=DATA_DIR / "files"),
            sqlite=SQLiteStorageConfig(path=DATA_DIR / "mnemo.db"),
            qdrant=QdrantStorageConfig(
                url=HttpUrl(qdrant_url),
                api_key=os.environ.get("MNEMO_STORAGE_QDRANT_API_KEY") or None,
                collection_name=COLLECTION_NAME,
                on_disk=False,
            ),
            surrealdb=SurrealDBStorageConfig(
                url=HttpUrl(surrealdb_url),
                username=os.environ.get(
                    "MNEMO_STORAGE_SURREALDB_USERNAME", surrealdb_defaults.username
                ),
                password=os.environ.get(
                    "MNEMO_STORAGE_SURREALDB_PASSWORD", surrealdb_defaults.password
                ),
                namespace="mnemo_manual_qa",
                database="gita_manual_qa",
            ),
        ),
        llm=LLMConfig(
            planner=role,
            synthesizer=role,
            extractor=role,
            classifier=role,
        ),
        embedding=EmbeddingConfig(
            provider="ollama",
            model=EMBEDDING_MODEL,
            dimensions=768,
            api_base=ollama_url,
        ),
        reranker=RerankerConfig(
            provider="sentence-transformers",
            model=RERANKER_MODEL,
        ),
        plugins=PluginConfig(directory=ROOT / "plugins"),
    )


async def _ensure_indexed(
    config: MnemoConfig, force_reindex: bool = False
) -> tuple[tuple[Chunk, ...], str, UUID, UUID]:
    """Ensure the Bhagavad Gita dataset is parsed and embedded into storage."""
    notebook_id = uuid5(NAMESPACE_URL, "mnemo-manual-qa:notebook")
    source_id = uuid5(NAMESPACE_URL, "mnemo-manual-qa:source")
    db_path = DATA_DIR / "mnemo.db"
    token_counter = O200KBaseTokenCounter(_tokenizer_asset())
    bootstrap_registry = _registry(config)

    if not force_reindex and db_path.exists():
        storage = bootstrap_registry.resolve_storage("primary")
        if storage is not None:
            await storage.open()
            try:
                page = await storage.list_documents(status=None, limit=1, cursor=None)
                if page.items:
                    doc = page.items[0]
                    current = next(
                        v for v in doc.versions if v.version_id == doc.current_version_id
                    )
                    title = current.metadata.title or "Bhagavad Gita"
                    parsed = await storage.get_parsed_document(current.version_id)
                    if parsed is not None:
                        from mnemo.chunkers import ChunkerDispatcher
                        from mnemo.interfaces import ChunkingContext, ChunkingOptions

                        dispatcher = ChunkerDispatcher(bootstrap_registry, token_counter)
                        ctx = ChunkingContext(
                            document_version=current,
                            options=ChunkingOptions(target_tokens=400, max_tokens=500),
                        )
                        chunks = dispatcher.dispatch(parsed, ctx)
                        await storage.close()
                        return chunks, title, notebook_id, source_id
            finally:
                await storage.close()

    import shutil

    if DATA_DIR.exists():
        for item in DATA_DIR.iterdir():
            if item.is_dir():
                shutil.rmtree(item)
            else:
                item.unlink()
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    print("[Setup] Freshly indexing Bhagavad Gita golden corpus into data/manual-gita-qa ...")
    bootstrap_registry = _registry(config)
    _m4, chunks, bootstrap_storage = await _run_m4(bootstrap_registry, config)
    document = await bootstrap_storage.get_document(chunks[0].document_id)
    if document is None:
        raise RuntimeError("Failed to retrieve parsed document")
    current = next(v for v in document.versions if v.version_id == document.current_version_id)
    title = current.metadata.title or "Bhagavad Gita"

    now = datetime.now(UTC)
    notebook = Notebook(
        notebook_id=notebook_id,
        title="Manual Bhagavad Gita QA",
        created_at=now,
        updated_at=now,
    )
    source = Source(
        source_id=source_id,
        notebook_id=notebook_id,
        document_id=chunks[0].document_id,
        created_at=now,
    )
    await bootstrap_storage.upsert_notebook(notebook)
    await bootstrap_storage.upsert_source(source)

    print("[Setup] Generating embeddings with nomic-embed-text into Qdrant ...")
    await bootstrap_registry.execute_startup_hooks()
    provider = bootstrap_registry.resolve_embedding_provider("primary")
    if provider is None:
        raise RuntimeError("Primary embedding provider not registered")

    from mnemo.embeddings.cached import CachedEmbeddingProvider
    from mnemo.embeddings.embedder import EmbedderModule
    from mnemo.storage.cache import SQLiteEmbeddingCache

    cache_path = DATA_DIR / "embedding-cache.db"
    cache = SQLiteEmbeddingCache(cache_path)
    await cache.initialize()
    cached_provider = CachedEmbeddingProvider(provider, cache)
    embedder = EmbedderModule(cached_provider, max_concurrency=4)

    embedded = await embedder.embed_chunks(chunks[:1000])
    await bootstrap_storage.upsert_chunks(embedded)
    print(f"[Setup] Ingestion complete: {len(chunks)} chunks, {len(embedded)} embedded & indexed.")
    await bootstrap_storage.close()
    return chunks, title, notebook_id, source_id


def _extract_chapter(heading_path: Sequence[str]) -> str:
    for heading in heading_path:
        upper = heading.upper()
        if "CHAPTER" in upper:
            return heading
    if len(heading_path) > 1:
        return heading_path[1]
    return heading_path[0] if heading_path else "Unknown"


def _extract_verse_heading(heading_path: Sequence[str]) -> str:
    for heading in reversed(heading_path):
        upper = heading.upper()
        if "TEXT" in upper or "VERSE" in upper:
            return heading
    return heading_path[-1] if heading_path else "Unknown"


_CHAPTER_NUM_TO_WORDS: dict[int, tuple[str, ...]] = {
    1: ("ONE", "1"),
    2: ("TWO", "2"),
    3: ("THREE", "3"),
    4: ("FOUR", "4"),
    5: ("FIVE", "5"),
    6: ("SIX", "6"),
    7: ("SEVEN", "7"),
    8: ("EIGHT", "8"),
    9: ("NINE", "9"),
    10: ("TEN", "10"),
    11: ("ELEVEN", "11"),
    12: ("TWELVE", "12"),
    13: ("THIRTEEN", "13"),
    14: ("FOURTEEN", "14"),
    15: ("FIFTEEN", "15"),
    16: ("SIXTEEN", "16"),
    17: ("SEVENTEEN", "17"),
    18: ("EIGHTEEN", "18"),
}


def _check_verse_verification(
    question: str,
    result: FinalQAResult | None,
) -> tuple[str, str]:
    """Check whether citations correspond to requested verse based on provenance."""
    if result is None:
        return "failed", "UNAVAILABLE"

    pipeline_status = (
        "citation_resolved"
        if result.status is FinalQAStatus.CITATION_RESOLVED
        else ("unmarked" if result.status is FinalQAStatus.UNMARKED else "failed")
    )

    # Check if question requests an exact chapter and verse
    match_dot = re.search(r"\b([1-9]|1[0-8])\.([0-9]{1,2})\b", question)
    match_text = re.search(
        r"Chapter\s+([1-9]|1[0-8]).*?(?:Verse|Text)\s+([0-9]{1,2})", question, re.IGNORECASE
    )

    req_chap: int | None = None
    req_verse: int | None = None
    if match_dot:
        req_chap = int(match_dot.group(1))
        req_verse = int(match_dot.group(2))
    elif match_text:
        req_chap = int(match_text.group(1))
        req_verse = int(match_text.group(2))

    if req_chap is None or req_verse is None:
        return pipeline_status, "N/A (Conceptual/Topic Query)"

    if not result.citations:
        return pipeline_status, "UNAVAILABLE (No citations resolved)"

    words = _CHAPTER_NUM_TO_WORDS.get(req_chap, (str(req_chap),))
    verse_patterns = [
        f"{req_chap}.{req_verse}",
        f"TEXT {req_verse}",
        f"VERSE {req_verse}",
        f"TEXTS {req_verse}",
    ]

    matched = False
    retrieved_provenances: list[str] = []
    for citation in result.citations:
        heading_joined = " ".join(citation.heading_path).upper()
        quote_upper = citation.verbatim_quote.upper()
        retrieved_provenances.append(f"{citation.heading_path} (page {citation.page_number})")

        has_chap = (
            any(f"CHAPTER {w}" in heading_joined for w in words)
            or f"BG {req_chap}" in heading_joined
        )
        has_verse = any(p in heading_joined or p in quote_upper for p in verse_patterns)

        if has_chap and has_verse:
            matched = True
            break

    if matched:
        return pipeline_status, f"VERIFIED (Retrieved Chapter {req_chap}, Verse {req_verse})"
    if retrieved_provenances:
        return (
            pipeline_status,
            f"NOT VERIFIED (Retrieved {len(result.citations)} non-matching citations)",
        )
    return pipeline_status, "UNAVAILABLE"


async def run_qa(
    engine: KnowledgeEngine,
    question: str,
    title: str,
    chunks: Sequence[Chunk],
    notebook_id: UUID,
    source_id: UUID,
    headings: tuple[str, ...],
    context_tokens: int,
    max_output_tokens: int,
) -> tuple[FinalQAResult | None, float, dict[str, object]]:
    """Execute a single query through the complete Mnemo Phase 0-6 RAG pipeline."""
    session_id = uuid4()
    user_turn_id = uuid4()
    assistant_turn_id = uuid4()
    now = datetime.now(UTC)

    with contextlib.suppress(Exception):
        await engine.storage.upsert_notebook(
            Notebook(
                notebook_id=notebook_id,
                created_at=now,
                updated_at=now,
                title="Manual Gita QA",
            )
        )

    with contextlib.suppress(Exception):
        await engine.storage.upsert_source(
            Source(
                source_id=source_id,
                notebook_id=notebook_id,
                document_id=chunks[0].document_id,
                created_at=now,
            )
        )

    user_turn = Turn(
        turn_id=user_turn_id,
        session_id=session_id,
        sequence=0,
        role=TurnRole.USER,
        content=question,
        created_at=now,
    )
    await engine.storage.upsert_session(
        Session(
            session_id=session_id,
            notebook_id=notebook_id,
            created_at=now,
            updated_at=now,
            title="Manual Gita QA Session",
            turns=(user_turn,),
        )
    )

    request = FinalQARequest(
        query=question,
        metadata_filter=MetadataFilter(
            notebook_id=notebook_id,
            source_ids=(source_id,),
            doc_types=(DocType.BOOK,),
        ),
        global_limit=6,
        context_budget=min(context_tokens - 2000, 6000),
        system_prompt="Answer only from the supplied Bhagavad Gita context.",
        max_output_tokens=max_output_tokens,
        session_id=session_id,
        user_turn_id=user_turn_id,
        assistant_turn_id=assistant_turn_id,
        table_of_contents=headings,
        source_titles=(title,),
        document_labels=(
            DocumentContextLabel(
                document_id=chunks[0].document_id,
                version_id=chunks[0].version_id,
                title=title,
            ),
        ),
    )

    start_time = time.perf_counter()
    try:
        result = await engine.final_qa.execute(request)
        latency = time.perf_counter() - start_time
        meta: dict[str, object] = {
            "session_id": str(session_id),
            "user_turn_id": str(user_turn_id),
            "assistant_turn_id": str(assistant_turn_id),
        }
        return result, latency, meta
    except Exception as exc:
        latency = time.perf_counter() - start_time
        meta = {"error": str(exc), "session_id": str(session_id)}
        return None, latency, meta


def print_qa_report(
    question: str,
    result: FinalQAResult | None,
    latency: float,
    context_tokens: int,
    max_output_tokens: int,
    title: str,
    target_doc_id: UUID,
    target_ver_id: UUID,
    meta: dict[str, object],
) -> dict[str, object]:
    """Print the complete human-readable evaluation report in exact required format."""
    print("\n" + "=" * 60)
    print("QUESTION")
    print("=" * 60)
    print(question)

    print("\n" + "=" * 60)
    print("GEMMA 4:e4b ANSWER")
    print("=" * 60)

    if result is None or not result.answer or not result.answer.strip():
        print("MODEL PRODUCED NO FINAL CONTENT")
        print("\nDiagnostic metadata:")
        print(f"  - error: {meta.get('error', 'Empty content returned by LLM')}")
        print(f"  - requested context_size: {context_tokens}")
        print(f"  - max_output_tokens: {max_output_tokens}")
        return {"non_empty": False, "markers_valid": False, "all_resolved": False}

    # Print EXACT answer verbatim - never private thinking
    print(result.answer)

    print("\n" + "=" * 60)
    print("CITATION RESOLUTION")
    print("=" * 60)

    if not result.citations:
        print("(No citations resolved)")
    else:
        for citation in result.citations:
            chapter = _extract_chapter(citation.heading_path)
            verse_heading = _extract_verse_heading(citation.heading_path)
            print(f"[source:{citation.source_number}]")
            print(f"  document: {title}")
            print(f"  chapter: {chapter}")
            print(f"  verse/heading if available: {verse_heading}")
            print(f"  page: {citation.page_number}")
            print(f"  chunk_id: {citation.chunk_id}")
            print(f"  citation_id: {citation.citation_id}")
            print(f"  canonical quote: {citation.verbatim_quote!r}")
            print()

    # Extract pipeline metadata
    answer_res = result.citation_result.answer_result
    ctx_res = answer_res.context_result
    gen_evidence = answer_res.generation_evidence
    rerank_res = ctx_res.rerank_result
    fusion_res = rerank_res.fusion_result

    prompt_tokens = ctx_res.context_tokens
    answer_tokens = gen_evidence.answer_token_count if gen_evidence is not None else 0
    retrieved_candidates = len(fusion_res.results)
    selected_context_items = len(ctx_res.items)
    compressed_items = sum(1 for it in ctx_res.items if it.kind is ContextItemKind.COMPRESSED)
    citation_count = len(result.citations)

    print("=" * 60)
    print("PIPELINE METADATA")
    print("=" * 60)
    print(f"- model: {MODEL}")
    print(f"- context size: {context_tokens}")
    print(f"- prompt tokens: {prompt_tokens}")
    print(f"- answer tokens: {answer_tokens}")
    print(f"- number of retrieved candidates: {retrieved_candidates}")
    print(f"- number of selected context items: {selected_context_items}")
    print(f"- number of compressed items: {compressed_items}")
    print(f"- number of citations: {citation_count}")
    print(f"- total latency: {latency:.2f}s")

    # Automated Checks & Verification
    pipeline_status, content_verification = _check_verse_verification(question, result)

    non_empty = bool(result.answer and result.answer.strip())
    all_resolved = result.status in (FinalQAStatus.CITATION_RESOLVED, FinalQAStatus.NO_CONTEXT)
    markers_valid = all_resolved
    citations_persisted = result.citation_result.persisted
    provenance_preserved = all(
        c.document_id == target_doc_id and c.version_id == target_ver_id for c in result.citations
    )
    valid_source_nums = {item.source_number for item in ctx_res.items}
    no_unknown = all(c.source_number in valid_source_nums for c in result.citations)
    within_bound = answer_tokens <= max_output_tokens

    print("\n" + "=" * 60)
    print("VERIFICATION & CHECKS")
    print("=" * 60)
    print(f"PIPELINE STATUS: {pipeline_status}")
    print(f"CONTENT VERIFICATION: {content_verification}")
    print()
    print(f"[{'PASS' if non_empty else 'FAIL'}] Non-empty answer")
    print(f"[{'PASS' if markers_valid else 'FAIL'}] Citation markers syntactically valid")
    print(f"[{'PASS' if all_resolved else 'FAIL'}] All markers resolve")
    print(f"[{'PASS' if citations_persisted else 'FAIL'}] Citations persisted")
    print(f"[{'PASS' if provenance_preserved else 'FAIL'}] Provenance preserved")
    print(f"[{'PASS' if no_unknown else 'FAIL'}] No unknown source numbers")
    print(f"[{'PASS' if within_bound else 'FAIL'}] Answer within output bound")
    print("\nHuman evaluation required: YES")
    print("=" * 60 + "\n")

    return {
        "non_empty": non_empty,
        "markers_valid": markers_valid,
        "all_resolved": all_resolved,
        "citations_persisted": citations_persisted,
        "provenance_preserved": provenance_preserved,
        "no_unknown": no_unknown,
        "within_bound": within_bound,
        "tokens": answer_tokens,
        "latency": latency,
        "pipeline_status": pipeline_status,
        "content_verification": content_verification,
    }


async def _run_batch_questions(
    engine: KnowledgeEngine,
    questions: dict[str, str],
    group_name: str,
    title: str,
    chunks: Sequence[Chunk],
    notebook_id: UUID,
    source_id: UUID,
    headings: tuple[str, ...],
    context_size: int,
    max_output: int,
    target_doc_id: UUID,
    target_ver_id: UUID,
) -> None:
    """Run a dictionary of questions in batch mode and display individual + summary reports."""
    total = len(questions)
    results: list[dict[str, object]] = []

    print(f"\n[Batch] Executing {group_name} ({total} questions) sequentially...\n")

    for i, (code, q) in enumerate(questions.items(), 1):
        print(f"\n>>> [{code}] Running Question {i}/{total}: {q}")
        res, lat, meta = await run_qa(
            engine,
            q,
            title,
            chunks,
            notebook_id,
            source_id,
            headings,
            context_size,
            max_output,
        )
        checks = print_qa_report(
            q,
            res,
            lat,
            context_size,
            max_output,
            title,
            target_doc_id,
            target_ver_id,
            meta,
        )
        results.append(checks)

    # Batch Summary
    success_count = sum(1 for r in results if r.get("non_empty"))
    failed_count = total - success_count
    resolved_count = sum(1 for r in results if r.get("all_resolved") and r.get("non_empty"))
    fail_citations = total - resolved_count
    verified_count = sum(1 for r in results if "VERIFIED" in str(r.get("content_verification", "")))
    valid_tokens = [int(str(r["tokens"])) for r in results if "tokens" in r]
    avg_tokens = sum(valid_tokens) / len(valid_tokens) if valid_tokens else 0.0
    valid_lats = [float(str(r["latency"])) for r in results if "latency" in r]
    avg_lat = sum(valid_lats) / len(valid_lats) if valid_lats else 0.0

    print("\n" + "=" * 60)
    print(f"BATCH SUMMARY — {group_name}")
    print("=" * 60)
    print(f"Questions attempted: {total}")
    print(f"Successful answers: {success_count}")
    print(f"Failed answers: {failed_count}")
    print(f"Citation-resolved answers: {resolved_count}")
    print(f"Citation failures: {fail_citations}")
    print(f"Content-verified answers: {verified_count}")
    print()
    print(f"Average latency: {avg_lat:.2f}s")
    print(f"Average answer tokens: {avg_tokens:.1f}")
    print("=" * 60 + "\n")


async def main() -> int:
    parser = argparse.ArgumentParser(
        description="Mnemo Phase 0-6 Manual Bhagavad Gita QA Test Suite"
    )
    parser.add_argument(
        "--context",
        type=int,
        default=8192,
        help="Context window size (e.g. 8192, 16384, 32768). Default: 8192",
    )
    parser.add_argument(
        "--max-output-tokens",
        type=int,
        default=1000,
        help="Maximum generated output tokens. Default: 1000",
    )
    parser.add_argument(
        "--question",
        "-q",
        type=str,
        default=None,
        help=(
            "Question code (e.g. C1-C15, S1-S27, T1-T18, K1-K10), 'all', "
            "'all-c', 'all-s', 'all-t', 'all-k', or custom question string"
        ),
    )
    parser.add_argument(
        "--reindex",
        action="store_true",
        help="Force fresh re-indexing of the Bhagavad Gita golden corpus",
    )
    args = parser.parse_args()

    context_size = args.context
    max_output = args.max_output_tokens

    print("=" * 60)
    print("Mnemo — Manual Bhagavad Gita QA")
    print(f"Model: {MODEL}")
    print(f"Context: {context_size}")
    print(f"Max Output Tokens: {max_output}")
    print("=" * 60)

    config = _build_config(context_size)
    chunks, title, notebook_id, source_id = await _ensure_indexed(
        config, force_reindex=args.reindex
    )

    token_counter = O200KBaseTokenCounter(_tokenizer_asset())
    engine = KnowledgeEngine(
        config,
        final_qa_components=FinalQAComponents(
            token_counter=token_counter, clock=lambda: datetime.now(UTC)
        ),
    )
    await engine.initialize()

    headings = tuple(
        dict.fromkeys(
            heading for chunk in chunks for heading in chunk.heading_path if heading.strip()
        )
    )[:40]
    target_doc_id = chunks[0].document_id
    target_ver_id = chunks[0].version_id

    try:
        if args.question is not None:
            choice = args.question.strip()
            upper_choice = choice.upper()

            if choice.lower() == "all":
                await _run_batch_questions(
                    engine,
                    ALL_QUESTIONS,
                    "ALL CATEGORIES",
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                    target_doc_id,
                    target_ver_id,
                )
            elif choice.lower() in ("all-c", "all_c", "conceptual"):
                await _run_batch_questions(
                    engine,
                    CONCEPTUAL_QUESTIONS,
                    "CONCEPTUAL QUESTIONS",
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                    target_doc_id,
                    target_ver_id,
                )
            elif choice.lower() in ("all-s", "all_s", "shloka", "verse"):
                await _run_batch_questions(
                    engine,
                    EXACT_SHLOKA_QUESTIONS,
                    "EXACT SHLOKA / VERSE QUESTIONS",
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                    target_doc_id,
                    target_ver_id,
                )
            elif choice.lower() in ("all-t", "all_t", "topic"):
                await _run_batch_questions(
                    engine,
                    TOPIC_SHLOKA_QUESTIONS,
                    "TOPIC → SHLOKA QUESTIONS",
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                    target_doc_id,
                    target_ver_id,
                )
            elif choice.lower() in ("all-k", "all_k", "karma"):
                await _run_batch_questions(
                    engine,
                    KARMA_GROUP_QUESTIONS,
                    "KARMA / KARMA-YOGA GROUP",
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                    target_doc_id,
                    target_ver_id,
                )
            elif upper_choice in ALL_QUESTIONS:
                q = ALL_QUESTIONS[upper_choice]
                res, lat, meta = await run_qa(
                    engine,
                    q,
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                )
                print_qa_report(
                    q,
                    res,
                    lat,
                    context_size,
                    max_output,
                    title,
                    target_doc_id,
                    target_ver_id,
                    meta,
                )
            elif choice.isdigit() and 1 <= int(choice) <= 15:
                # Backward compatibility: 1-15 maps to C1-C15
                code = f"C{int(choice)}"
                q = CONCEPTUAL_QUESTIONS[code]
                res, lat, meta = await run_qa(
                    engine,
                    q,
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                )
                print_qa_report(
                    q,
                    res,
                    lat,
                    context_size,
                    max_output,
                    title,
                    target_doc_id,
                    target_ver_id,
                    meta,
                )
            else:
                # Custom question directly passed
                res, lat, meta = await run_qa(
                    engine,
                    choice,
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                )
                print_qa_report(
                    choice,
                    res,
                    lat,
                    context_size,
                    max_output,
                    title,
                    target_doc_id,
                    target_ver_id,
                    meta,
                )
            return 0

        # Interactive Mode
        while True:
            print("\n" + "=" * 60)
            print("MNEMO — MANUAL BHAGAVAD GITA QA")
            print("=" * 60)

            for cat_name, questions in ALL_CATEGORIES.items():
                print(f"\n{cat_name}")
                print("-" * len(cat_name))
                for code, q in questions.items():
                    print(f"  {code:>3}. {q}")

            print("\nBATCH EXECUTION")
            print("---------------")
            print("  all    : Run all questions across all categories")
            print("  all-c  : Run all conceptual questions (C1-C15)")
            print("  all-s  : Run all exact shloka questions (S1-S27)")
            print("  all-t  : Run all topic->shloka questions (T1-T18)")
            print("  all-k  : Run all karma group questions (K1-K10)")

            print("\nCUSTOM & QUIT")
            print("-------------")
            print("  custom / X : Enter your own custom question")
            print("  q / quit   : Exit")
            print()

            try:
                raw = input("Enter choice > ").strip()
            except (EOFError, KeyboardInterrupt):
                print("\nExiting.")
                break

            if not raw or raw.lower() in ("q", "quit", "exit"):
                print("Exiting.")
                break

            upper_raw = raw.upper()

            if raw.lower() == "all":
                await _run_batch_questions(
                    engine,
                    ALL_QUESTIONS,
                    "ALL CATEGORIES",
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                    target_doc_id,
                    target_ver_id,
                )
            elif raw.lower() in ("all-c", "all_c", "conceptual"):
                await _run_batch_questions(
                    engine,
                    CONCEPTUAL_QUESTIONS,
                    "CONCEPTUAL QUESTIONS",
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                    target_doc_id,
                    target_ver_id,
                )
            elif raw.lower() in ("all-s", "all_s", "shloka", "verse"):
                await _run_batch_questions(
                    engine,
                    EXACT_SHLOKA_QUESTIONS,
                    "EXACT SHLOKA / VERSE QUESTIONS",
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                    target_doc_id,
                    target_ver_id,
                )
            elif raw.lower() in ("all-t", "all_t", "topic"):
                await _run_batch_questions(
                    engine,
                    TOPIC_SHLOKA_QUESTIONS,
                    "TOPIC → SHLOKA QUESTIONS",
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                    target_doc_id,
                    target_ver_id,
                )
            elif raw.lower() in ("all-k", "all_k", "karma"):
                await _run_batch_questions(
                    engine,
                    KARMA_GROUP_QUESTIONS,
                    "KARMA / KARMA-YOGA GROUP",
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                    target_doc_id,
                    target_ver_id,
                )
            elif raw.lower() in ("custom", "x"):
                try:
                    custom_q = input("\nEnter your question:\n> ").strip()
                except (EOFError, KeyboardInterrupt):
                    continue
                if not custom_q:
                    print("Empty question ignored.")
                    continue
                res, lat, meta = await run_qa(
                    engine,
                    custom_q,
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                )
                print_qa_report(
                    custom_q,
                    res,
                    lat,
                    context_size,
                    max_output,
                    title,
                    target_doc_id,
                    target_ver_id,
                    meta,
                )
            elif upper_raw in ALL_QUESTIONS:
                q = ALL_QUESTIONS[upper_raw]
                res, lat, meta = await run_qa(
                    engine,
                    q,
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                )
                print_qa_report(
                    q,
                    res,
                    lat,
                    context_size,
                    max_output,
                    title,
                    target_doc_id,
                    target_ver_id,
                    meta,
                )
            elif raw.isdigit() and 1 <= int(raw) <= 15:
                code = f"C{int(raw)}"
                q = CONCEPTUAL_QUESTIONS[code]
                res, lat, meta = await run_qa(
                    engine,
                    q,
                    title,
                    chunks,
                    notebook_id,
                    source_id,
                    headings,
                    context_size,
                    max_output,
                )
                print_qa_report(
                    q,
                    res,
                    lat,
                    context_size,
                    max_output,
                    title,
                    target_doc_id,
                    target_ver_id,
                    meta,
                )
            else:
                print(
                    f"Invalid option: {raw!r}. Please enter a valid code (e.g. C1, S1, T1, K1), "
                    "batch command (all, all-c, all-s, all-t, all-k), custom, or q."
                )

    finally:
        await engine.shutdown()

    return 0


if __name__ == "__main__":
    asyncio.run(main())
