"""Public Phase 1 Module 1.2 interface contracts."""

from .cache import CacheInterface, CacheInterfaceV1
from .chunker import ChunkerInterface, ChunkerInterfaceV1, ChunkerInterfaceV2
from .embedding import EmbeddingProvider, EmbeddingProviderV1
from .errors import (
    ConflictError,
    ContractValidationError,
    DependencyUnavailableError,
    IntegrityError,
    LifecycleError,
    MnemoInterfaceError,
    NotFoundError,
    OperationCancelledError,
    OperationTimeoutError,
    PluginError,
    StorageError,
    UnsupportedError,
)
from .final_qa import FinalQAInterface, FinalQAInterfaceV1
from .final_qa_execution import FinalQAExecutionStoreV1
from .fusion_reranker import FusionRerankingInterface, FusionRerankingInterfaceV1
from .llm import LLMInterface, LLMInterfaceV1
from .multi_source_retrieval import (
    MultiSourceRetrievalInterface,
    MultiSourceRetrievalInterfaceV1,
)
from .parent_promotion import ParentPromotionInterface, ParentPromotionInterfaceV1
from .parser import ParserInterface, ParserInterfaceV1
from .reranker import RerankerInterface, RerankerInterfaceV1
from .retriever import RetrieverInterface, RetrieverInterfaceV1
from .storage import StorageInterface, StorageInterfaceV1
from .tokenizer import TokenCounterInterfaceV1
from .types import (
    ChunkerCapabilities,
    ChunkingContext,
    ChunkingOptions,
    CompletionResult,
    EmbeddingBatch,
    EmbeddingCapabilities,
    EmbeddingVector,
    FileMetadata,
    FusionRerankerCapabilities,
    HealthStatus,
    LLMCapabilities,
    Message,
    MessageRole,
    Page,
    ParentPromotionCapabilities,
    ParserCapabilities,
    RerankerCapabilities,
    RetrieverCapabilities,
    StorageCapabilities,
)
from .versions import (
    CHUNKER_INTERFACE_V2_VERSION,
    CHUNKER_INTERFACE_VERSION,
    EMBEDDING_PROVIDER_INTERFACE_VERSION,
    FUSION_RERANKER_INTERFACE_VERSION,
    LLM_INTERFACE_VERSION,
    PARENT_PROMOTION_INTERFACE_VERSION,
    PARSER_INTERFACE_VERSION,
    RERANKER_INTERFACE_VERSION,
    RETRIEVER_INTERFACE_VERSION,
    STORAGE_INTERFACE_VERSION,
)

__all__ = [
    "CHUNKER_INTERFACE_V2_VERSION",
    "CHUNKER_INTERFACE_VERSION",
    "EMBEDDING_PROVIDER_INTERFACE_VERSION",
    "FUSION_RERANKER_INTERFACE_VERSION",
    "LLM_INTERFACE_VERSION",
    "PARENT_PROMOTION_INTERFACE_VERSION",
    "PARSER_INTERFACE_VERSION",
    "RERANKER_INTERFACE_VERSION",
    "RETRIEVER_INTERFACE_VERSION",
    "STORAGE_INTERFACE_VERSION",
    "CacheInterface",
    "CacheInterfaceV1",
    "ChunkerCapabilities",
    "ChunkerInterface",
    "ChunkerInterfaceV1",
    "ChunkerInterfaceV2",
    "ChunkingContext",
    "ChunkingOptions",
    "CompletionResult",
    "ConflictError",
    "ContractValidationError",
    "DependencyUnavailableError",
    "EmbeddingBatch",
    "EmbeddingCapabilities",
    "EmbeddingProvider",
    "EmbeddingProviderV1",
    "EmbeddingVector",
    "FileMetadata",
    "FinalQAExecutionStoreV1",
    "FinalQAInterface",
    "FinalQAInterfaceV1",
    "FusionRerankerCapabilities",
    "FusionRerankingInterface",
    "FusionRerankingInterfaceV1",
    "HealthStatus",
    "IntegrityError",
    "LLMCapabilities",
    "LLMInterface",
    "LLMInterfaceV1",
    "LifecycleError",
    "Message",
    "MessageRole",
    "MnemoInterfaceError",
    "MultiSourceRetrievalInterface",
    "MultiSourceRetrievalInterfaceV1",
    "NotFoundError",
    "OperationCancelledError",
    "OperationTimeoutError",
    "Page",
    "ParentPromotionCapabilities",
    "ParentPromotionInterface",
    "ParentPromotionInterfaceV1",
    "ParserCapabilities",
    "ParserInterface",
    "ParserInterfaceV1",
    "PluginError",
    "RerankerCapabilities",
    "RerankerInterface",
    "RerankerInterfaceV1",
    "RetrieverCapabilities",
    "RetrieverInterface",
    "RetrieverInterfaceV1",
    "StorageCapabilities",
    "StorageError",
    "StorageInterface",
    "StorageInterfaceV1",
    "TokenCounterInterfaceV1",
    "UnsupportedError",
]
